---

version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    image: lysergia/sleepanarchy-nginx:latest
    networks:
      - frontend
    # TODO: map 80:80 & 443:443
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
      prerender:
        condition: service_healthy
    volumes:
      - media:/www/media:ro
  prerender:
    build:
      context: .
      dockerfile: deploy/prerender/Dockerfile
    image: lysergia/sleepanarchy-prerender:latest
    hostname: prerender
    networks:
      - frontend
    environment:
      CACHE_MAXSIZE: 1000
      CACHE_TTL: 1800
  api:
    build:
      context: .
      dockerfile: deploy/api/Dockerfile
    image: lysergia/sleepanarchy-api:latest
    tty: true
    hostname: api
    networks:
      - frontend
      - backend
    environment:
      - ENVIRONMENT=Production
      - DB_HOST=db
      - MEDIA_DIRECTORY=/srv/media
    volumes:
      - media:/srv/media:rw
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    hostname: db
    networks:
      - backend
    environment:
      - POSTGRES_USER=sleepanarchy-blog
      - POSTGRES_DB=sleepanarchy-blog
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sleepanarchy-blog -d sleepanarchy-blog"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  frontend:
  backend:

volumes:
  db:
  media:
