---

defaults: &defaults
  dialect: postgres
  datasource: dbname=sleepanarchy-blog user=sleepanarchy-blog sslmode=disable
  dir: migrations
  table: migrations

development:
  <<: *defaults

production:
  <<: *defaults
  datasource: host=db dbname=sleepanarchy-blog user=sleepanarchy-blog sslmode=disable
