---

name:
    sleepanarchy-api
version:
    0.1.0.0
github:
    prikhi/sleepanarchy
homepage:
    https://github.com/prikhi/sleepanarchy#readme
license:
    GPL-3.0-or-later
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2022 Pavan Rikhi
category:
    Web
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    API Server for <https://sleepanarchy.com>.

description: |
    This project contains the API definiton, route handlers, & database spec
    for the API hosted at https://sleepanarchy.com/api/. It provides
    functionality for Blog Posts, Link Sharing, & File Uploads.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        []

executables:
    sleepanarchy-api:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - sleepanarchy-api

tests:
    sleepanarchy-api-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - sleepanarchy-api
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
