---

name:
    sleepanarchy-api
version:
    0.1.0.0
github:
    prikhi/sleepanarchy
homepage:
    https://github.com/prikhi/sleepanarchy#readme
license:
    GPL-3.0-or-later
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2022 Pavan Rikhi
category:
    Web
language:
    GHC2021
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    API Server for <https://sleepanarchy.com>.

description: |
    This project contains the API definiton, route handlers, & database spec
    for the API hosted at https://sleepanarchy.com/api/. It provides
    functionality for Blog Posts, Link Sharing, & File Uploads.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wimplicit-lift
    - -Wmissing-exported-signatures
    - -Wredundant-bang-patterns
    - -Wredundant-constraints
    - -Wunused-packages
    - -Wunused-type-patterns
    - -O2

default-extensions:
    - DataKinds
    - LambdaCase
    - MonoLocalBinds
    - MultiWayIf
    - OverloadedStrings
    - QuasiQuotes
    - ViewPatterns


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        - aeson
        - base64
        - bytestring
        - containers
        - cookie
        - directory
        - esqueleto
        - filepath
        - http-media
        - jose
        - lens
        - mime-types
        - monad-logger
        - mtl
        - password
        - persistent
        - persistent-postgresql
        - raw-strings-qq
        - resource-pool
        - safe-exceptions
        - servant
        - servant-auth-docs
        - servant-auth-server
        - servant-docs
        - servant-server
        - sitemap-gen
        - stm
        - text
        - time
        - wai-extra

executables:
    sleepanarchy-api:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - sleepanarchy-api
            - warp

    sleepanarchy-api-management:
        source-dirs:
            management
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - sleepanarchy-api
            - aeson
            - mtl
            - password
            - persistent
            - postgresql-simple
            - safe-exceptions
            - servant-auth-server
            - text

tests:
    sleepanarchy-api-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - sleepanarchy-api
            - aeson
            - bytestring
            - filepath
            - hedgehog
            - monad-logger
            - mtl
            - persistent
            - persistent-postgresql
            - resource-pool
            - safe-exceptions
            - servant-server
            - stm
            - tasty
            - tasty-hedgehog
            - tasty-hunit
            - time
            - text
            - unordered-containers
