---
# yamllint disable rule:line-length

name: CI Build

# yamllint disable-line rule:truthy
on:
  # Run Daily
  schedule:
    - cron: '0 0 * * *'
  # Run on Push
  push:
  # Run on Tag Creation
  create:
  # Allow Running Manually
  workflow_dispatch:

jobs:
  build-stack:
    name: Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Stack Artifacts
        uses: actions/cache@v2
        with:
          key: stack-build-lts-${{ github.ref }}-${{ github.sha }}
          path: |
            ~/.stack/
            sleepanarchy-api/.stack-work/
          restore-keys: |
            stack-build-lts-${{ github.ref }}-
            stack-build-lts-
            stack-build-
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
      - run: cd sleepanarchy-api && stack test --fast --haddock --pedantic --resolver lts-18

  # Stackage Nightly - Failures Allowed
  build-nightly:
    name: Stackage Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Current Date
        id: date
        run: echo -e "::set-output name=year::$(date +%Y)\n::set-output name=month::$(date +%m)\n::set-output name=day::$(date +%d)"
      - name: Cache Stack Artifacts
        uses: actions/cache@v2
        with:
          key: stack-build-nightly-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }}-${{ github.ref }}-${{ github.sha }}
          path: |
            ~/.stack/
            sleepanarchy-api/.stack-work/
          restore-keys: |
            stack-build-nightly-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }}-${{ github.ref }}-
            stack-build-nightly-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }}-
            stack-build-nightly-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-
            stack-build-nightly-${{ steps.date.outputs.year }}-
            stack-build-nightly-
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
      - run: cd sleepanarchy-api && stack test --fast --haddock --pedantic --resolver nightly
        continue-on-error: true

  # Cabal Builds w/ Current & Next GHC
  build-cabal:
    name: GHC / Cabal
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.0', '9.2']
    steps:
      - uses: actions/checkout@v3
      - name: Cache Cabal Artifacts
        uses: actions/cache@v2
        with:
          key: cabal-build-${{ matrix.ghc }}-${{ github.ref }}-${{ github.sha }}
          path: |
            ~/.cabal/packages/
            ~/.cabal/store
            dist-newstyle/
          restore-keys: |
            cabal-build-${{ matrix.ghc }}-${{ github.ref }}-
            cabal-build-${{ matrix.ghc }}-
            cabal-build-
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest
          enable-stack: true
      - run: cabal update
      - run: cd sleepanarchy-api && cabal new-test --enable-tests && cabal new-haddock

  # Build the Frontend
  build-purescript:
    name: PureScript / Webpack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache PureScript Artifacts
        uses: actions/cache@v2
        with:
          key: spago-${{ github.ref }}-${{ github.sha }}
          path: |
            sleepanarchy-website/.spago
            sleepanarchy-website/output
          restore-keys: |
            spago-${{ github.ref }}-
            spago-
      - uses: actions/setup-node@v3
        with:
          node-version-file: sleepanarchy-website/.nvmrc
          cache: npm
          cache-dependency-path: sleepanarchy-website/package-lock.json
      - run: cd sleepanarchy-website && npm ci
      - run: cd sleepanarchy-website && npm build
